### ISSUE TITLE
Porn list

### ISSUE THREAD

**Issue by DNDEBUG** [1boii/hosts#1]
Not as well organized of a list as i wanted to be, github's fault
you must use a url crawler to grab addresses
there are some comments, read them
every site has been tested, some aren't working for some reason now, but i have confirmed they have porn
some related sites got separated in the list because the sorting
for time sake i have not tested them against other lists
there might be some site from my own list, i tried to remove them but there might still be one in the list
some sites include their language associated addresses
some sites don't work without www, some do, they should be tested with and without www
some sites with www will still work if they don't have wwww
and some sites without www will still work if www is added
yandex is really good at finding porn sites, you should try 

0.0.0.0 www.hentaisun.com
0.0.0.0 rule34video.party
0.0.0.0 equibooru.eu
0.0.0.0 equibooru.gq
0.0.0.0 equibooru.uk.to
0.0.0.0 equibooru.us.to
0.0.0.0 www.zoovilleforum.net
0.0.0.0 beast.chat
0.0.0.0 zoophilia.wiki
0.0.0.0 beastbooru.com
0.0.0.0 equibooru.int.eu.org
0.0.0.0 zoostories.farm
0.0.0.0 beasttracker.dog
0.0.0.0 www.forumzoone.org
0.0.0.0 hypnotube.callabitch.org
0.0.0.0 jessicarasbandhomes.com
0.0.0.0 thebesthentai.com
0.0.0.0 xxxgamer.net
0.0.0.0 hentaihorizon.com
0.0.0.0 www.hentairider.com
0.0.0.0 booth.pm
0.0.0.0 shop.peeing-outdoors.com
0.0.0.0 peeing-outdoors.com
0.0.0.0 blowboobs.com
0.0.0.0 th.hentai-img.com
0.0.0.0 static1.hentai-img.com
0.0.0.0 static2.hentai-img.com
0.0.0.0 static3.hentai-img.com
0.0.0.0 static4.hentai-img.com
0.0.0.0 static5.hentai-img.com
0.0.0.0 static6.hentai-img.com
0.0.0.0 static7.hentai-img.com
0.0.0.0 static8.hentai-img.com
0.0.0.0 static9.hentai-img.com
0.0.0.0 static10.hentai-img.com
0.0.0.0 static11.hentai-img.com
0.0.0.0 static12.hentai-img.com
0.0.0.0 static13.hentai-img.com
0.0.0.0 static14.hentai-img.com
0.0.0.0 static15.hentai-img.com
0.0.0.0 static16.hentai-img.com
0.0.0.0 static17.hentai-img.com
0.0.0.0 static18.hentai-img.com
0.0.0.0 static19.hentai-img.com
0.0.0.0 static20.hentai-img.com
0.0.0.0 www.hacg.cat
0.0.0.0 fresasdeeuropa.eu
0.0.0.0 www.nakedskins.com
0.0.0.0 www.taylorswiftipsum.com
0.0.0.0 filmesporno.xxx
0.0.0.0 www.metrophilasurgeons.org
0.0.0.0 hotgta.com
0.0.0.0 0cili.com
0.0.0.0 0magnet.com
0.0.0.0 1024ph.com
0.0.0.0 1080p.av4.club
0.0.0.0 17rub.ru
0.0.0.0 18comic.org
0.0.0.0 24rolika.ru
0.0.0.0 3dfutaporn.com
0.0.0.0 3mag.net
0.0.0.0 4edit.booru.org
0.0.0.0 628701.site123.me
0.0.0.0 69dsp.tv
0.0.0.0 7mag.net
0.0.0.0 91mh.co
0.0.0.0 9mag.net
0.0.0.0 a.xxxlibz.com
0.0.0.0 ab.av4.club
0.0.0.0 absolutesexdoll.com
0.0.0.0 adoujin.com
0.0.0.0 adult-comics.1hentai.org
0.0.0.0 adult-hot-games.life
0.0.0.0 adultcomicbook.net
0.0.0.0 adultgames.games
0.0.0.0 adultnode.com
0.0.0.0 adulttoymegastore.com
0.0.0.0 americansexdolls.com
0.0.0.0 amibooru.booru.org
0.0.0.0 analchiks.com
0.0.0.0 andreauntamed.com
0.0.0.0 animatedfemuscles.booru.org
0.0.0.0 animehentaihub.com
0.0.0.0 api-cdn.rule34.xxx # CDN for rule34.xxx
0.0.0.0 asianpornwebsites.com
0.0.0.0 asiantraps.com
0.0.0.0 av.av4.club
0.0.0.0 av4.club
0.0.0.0 avlang.com
0.0.0.0 aziani.com
0.0.0.0 b989.tv
0.0.0.0 badfolder.com
0.0.0.0 baraag.net
0.0.0.0 bbc-anal.com
0.0.0.0 bestporncomix.com
0.0.0.0 bigassfetish.com
0.0.0.0 bigasshoz.com
0.0.0.0 blackporn24.com
0.0.0.0 bleachbooru.org
0.0.0.0 blowjobcumshots.com
0.0.0.0 blowjobgif.net
0.0.0.0 bondagecomixxx.net
0.0.0.0 boobsrealm.com
0.0.0.0 bookitlab.tech
0.0.0.0 booru.foalcon.com
0.0.0.0 booru.io
0.0.0.0 booru.xxx
0.0.0.0 buzzboy.net
0.0.0.0 captions.booru.org
0.0.0.0 cartoonporncomix.com
0.0.0.0 cartoonregistry.com
0.0.0.0 cartoontube69.com
0.0.0.0 celeraprime.booru.org
0.0.0.0 chastitygurls.bdsmlr.com
0.0.0.0 cityspirits.eu
0.0.0.0 cliniqueregain.com
0.0.0.0 cm.isger.de
0.0.0.0 cmstuff.bumboom.de
0.0.0.0 cn.av4.club
0.0.0.0 cn.jpg4.biz
0.0.0.0 collection-nu.com
0.0.0.0 comicbooksgalaxy.com
0.0.0.0 comicbooksex.com
0.0.0.0 comicporn.xxx
0.0.0.0 comicporntoons.com
0.0.0.0 comicsarmy.com
0.0.0.0 comicsporno.top
0.0.0.0 comicsvalley.com
0.0.0.0 comxmag.com
0.0.0.0 content.bigasshoz.com
0.0.0.0 coomer.party
0.0.0.0 crazyporn.xxx
0.0.0.0 cumanga.com
0.0.0.0 cure.ninja
0.0.0.0 damochki.net
0.0.0.0 data.jpg4.biz
0.0.0.0 de.av4.club
0.0.0.0 de.hentai-img.com
0.0.0.0 de.jpg4.biz
0.0.0.0 de.xhwide2.com
0.0.0.0 deadlime.com
0.0.0.0 deepfake-porn.com
0.0.0.0 dirtycomics69.com
0.0.0.0 dirtydrawing.com
0.0.0.0 dirtyleague.com
0.0.0.0 ditnhe.xyz
0.0.0.0 docs.hentai.xxx
0.0.0.0 doll-stuffing.booru.org
0.0.0.0 doujin69.com
0.0.0.0 dydqxf.com
0.0.0.0 dysp7.me
0.0.0.0 ecchi.iwara.tv
0.0.0.0 el124.com
0.0.0.0 en.av4.club
0.0.0.0 en.jpg4.biz
0.0.0.0 ero-comic-hunter.net
0.0.0.0 ero-teca.blogspot.com
0.0.0.0 erocomicsxxx.com
0.0.0.0 erogames.com
0.0.0.0 eropix.net
0.0.0.0 es.av4.club
0.0.0.0 es.hentai-img.com
0.0.0.0 es.jpg4.biz
0.0.0.0 es.xhwide2.com
0.0.0.0 escortsporn.com
0.0.0.0 famoustoonsporn.com
0.0.0.0 fanbox.cc
0.0.0.0 fapdrop.com
0.0.0.0 fapetite.com
0.0.0.0 fapreactor.com
0.0.0.0 faptitans.com
0.0.0.0 fareastpornhub.com
0.0.0.0 feetwonder.com
0.0.0.0 findbare.com
0.0.0.0 free-3d-porn.com
0.0.0.0 freeadultcomix69.com
0.0.0.0 freedomwings-project.eu
0.0.0.0 freefutatoons.com
0.0.0.0 freejabcomics.com
0.0.0.0 freejavjav.com
0.0.0.0 freejavunc.com
0.0.0.0 freesexgames.games
0.0.0.0 freshmeat.io
0.0.0.0 fsayadoujin.com
0.0.0.0 fuckcomics.net
0.0.0.0 fundorado.de
0.0.0.0 funtracerblog.blogspot.com
0.0.0.0 futahentai.org
0.0.0.0 futanaria.com
0.0.0.0 futanariasex.com
0.0.0.0 futapo.com
0.0.0.0 futureporn.net
0.0.0.0 gamesofdesired.com
0.0.0.0 gesek.net
0.0.0.0 getcomixxx.com
0.0.0.0 getmag.net
0.0.0.0 gettube.co
0.0.0.0 giantessbooru.com
0.0.0.0 gidolik.ru
0.0.0.0 globalcomix.blogspot.com
0.0.0.0 hairykitten.com
0.0.0.0 hanime.xxx
0.0.0.0 helltaker.booru.org
0.0.0.0 hentai-moon.com
0.0.0.0 hentai-zona.com
0.0.0.0 hentai.desi
0.0.0.0 hentai.xxx
0.0.0.0 hentaicentro.com
0.0.0.0 hentaicoins.com
0.0.0.0 hentaimania.me
0.0.0.0 hentaiprn.com
0.0.0.0 hentaireviews.moe
0.0.0.0 hentairox.com
0.0.0.0 hentaithai.com
0.0.0.0 hentaixuz.blogspot.com
0.0.0.0 hentaixxxmanga.com
0.0.0.0 hentaizilla.com
0.0.0.0 hiddenhomemade.com
0.0.0.0 hornygrail.com
0.0.0.0 hot2048.com
0.0.0.0 hotcelebritiesandbabes.blogspot.com
0.0.0.0 huaqun88.com
0.0.0.0 hugetits.win
0.0.0.0 hycgame8.xyz
0.0.0.0 id.hentai-img.com
0.0.0.0 img.jpg4.bi
0.0.0.0 img.mizugi.pro
0.0.0.0 imhentai.xxx
0.0.0.0 inin17.bar
0.0.0.0 iwara.tv
0.0.0.0 ja.hentai-img.com
0.0.0.0 jabcomix-porn.com
0.0.0.0 jav-angel.net
0.0.0.0 javenglish.cc
0.0.0.0 javfree.asia
0.0.0.0 javgg.net
0.0.0.0 javguruhd.com
0.0.0.0 javhd.com
0.0.0.0 javhd247.net
0.0.0.0 javhdfilms.com
0.0.0.0 javhdmost.com
0.0.0.0 javhdmost.com
0.0.0.0 javhdworld.com
0.0.0.0 javhub.com
0.0.0.0 javonline.watch
0.0.0.0 javonline.watch
0.0.0.0 javshujin.com
0.0.0.0 jksp70.cc
0.0.0.0 joi.booru.org
0.0.0.0 jp.av4.club
0.0.0.0 jp.jpg4.biz
0.0.0.0 jp.xhwide2.com
0.0.0.0 jpg4.biz
0.0.0.0 kawaiihentai.com
0.0.0.0 kemono.party
0.0.0.0 kinkazoid.com
0.0.0.0 ko.hentai-img.com
0.0.0.0 kr.av4.club
0.0.0.0 kr.jpg4.biz
0.0.0.0 kurosearch.vercel.app
0.0.0.0 kurozenzen.github.io
0.0.0.0 kusolove.bdsmlr.com
0.0.0.0 landing.eritonetwork.com
0.0.0.0 leakxxx.com
0.0.0.0 ledaotv.com
0.0.0.0 lewdzone.com
0.0.0.0 lm1.motherless.com
0.0.0.0 lp1.sexyemulator.com
0.0.0.0 lp2.sexyemulator.com
0.0.0.0 lp3.sexyemulator.com
0.0.0.0 m.lfacg520.com
0.0.0.0 m.smutty.com
0.0.0.0 m6.booru.org
0.0.0.0 makiacreative.com
0.0.0.0 manga.sexy
0.0.0.0 mangazuki.co
0.0.0.0 manhwapdf.blogspot.com
0.0.0.0 mauoo.com
0.0.0.0 megaboobsgirls.com
0.0.0.0 megainterracialcomics.com
0.0.0.0 members.hentai.xxx
0.0.0.0 mhentai.net
0.0.0.0 midobooru.midov.pl
0.0.0.0 midov.pl
0.0.0.0 milfjav.com
0.0.0.0 missuntamed.com
0.0.0.0 mmballbusting.booru.org
0.0.0.0 mmda.booru.org
0.0.0.0 moeimg.net
0.0.0.0 mp3.youtube4download.space
0.0.0.0 mvfc22.com
0.0.0.0 mypornads.com
0.0.0.0 nhentai.io
0.0.0.0 niadd.com
0.0.0.0 nudepussy.live
0.0.0.0 nutaku.net
0.0.0.0 ohjav.com
0.0.0.0 opensharing.org
0.0.0.0 owohho.com
0.0.0.0 p.yaoihavenreborn.com
0.0.0.0 panda.chaika.moe
0.0.0.0 parnuxi.com
0.0.0.0 photo.x-busty.org
0.0.0.0 pic.pornosok.ru
0.0.0.0 pl.sex.com
0.0.0.0 planetporno.de
0.0.0.0 pocketwaifus.io
0.0.0.0 porn7.net
0.0.0.0 pornaffiliate.xxx
0.0.0.0 pornaroma.com
0.0.0.0 porncomicsfree.net
0.0.0.0 porncomixinfo.net
0.0.0.0 porncomixone.net
0.0.0.0 porngames.com
0.0.0.0 porngames.games
0.0.0.0 porngameshub.com
0.0.0.0 porngeek.com
0.0.0.0 porngifs.xxx
0.0.0.0 pornleech.ch
0.0.0.0 pornocomics.net
0.0.0.0 pornogifs.net
0.0.0.0 pornoslab.com
0.0.0.0 pornosok.ru
0.0.0.0 pornotorrent.eu
0.0.0.0 pornpair.com
0.0.0.0 pornpander.com
0.0.0.0 pornpic.xxx
0.0.0.0 pornreactor.cc
0.0.0.0 pornrips.to
0.0.0.0 prettyanalsex.bdsmlr.com
0.0.0.0 prettyfemme.bdsmlr.com
0.0.0.0 pt.xhwide2.com
0.0.0.0 public-sex-porn.com
0.0.0.0 pururin.to
0.0.0.0 pusooy.net
0.0.0.0 qualityadultaffiliates.com
0.0.0.0 r18lu.com
0.0.0.0 r34hub.com
0.0.0.0 r34porn.net
0.0.0.0 raws.mangazuki.co
0.0.0.0 rcv.johren.net
0.0.0.0 realelders.com
0.0.0.0 reallifelovedolls.com
0.0.0.0 redheadporntube.com
0.0.0.0 redvids.net
0.0.0.0 rencontresanslendemain.net
0.0.0.0 retrodrawing.com
0.0.0.0 rintor.net
0.0.0.0 rokuhentai.com
0.0.0.0 romantic-sex-video.com
0.0.0.0 romy-star.blogspot.com
0.0.0.0 ru.av4.club
0.0.0.0 ru.hentai-img.com
0.0.0.0 ru.jpg4.biz
0.0.0.0 ru.sex.com
0.0.0.0 ru.xhwide2.com
0.0.0.0 rule34.us
0.0.0.0 rule34video.party
0.0.0.0 saveporno.com
0.0.0.0 scatbooru.co.uk
0.0.0.0 sexadultcomics.com
0.0.0.0 sexangelbaby.com
0.0.0.0 sexcomix.net
0.0.0.0 sexdollcenter.vip
0.0.0.0 sexdollgenie.com
0.0.0.0 sexdollpornhd.com
0.0.0.0 sexecoast.com
0.0.0.0 sexgymnastics.com
0.0.0.0 sexo.videomaniaco.com
0.0.0.0 sexporncomics.com
0.0.0.0 sextoy.com.br
0.0.0.0 sexwall.me
0.0.0.0 sexwhatelse.centerblog.net
0.0.0.0 sexxi.club
0.0.0.0 sfmcompile.club
0.0.0.0 sheetblowjob.com
0.0.0.0 shorty.booru.org
0.0.0.0 slotbitches.com
0.0.0.0 snow-plus.net
0.0.0.0 south-plus.net
0.0.0.0 sph.booru.org
0.0.0.0 sss.booru.org
0.0.0.0 subjav.tv
0.0.0.0 subscribestar.adult
0.0.0.0 svscomics.club
0.0.0.0 svscomics.com
0.0.0.0 sydneyrobertscd.bdsmlr.com
0.0.0.0 tags.literotica.com
0.0.0.0 tbib.org
0.0.0.0 telegra.ph
0.0.0.0 th.av4.club
0.0.0.0 th.jpg4.biz
0.0.0.0 thaiseaw.com
0.0.0.0 theowlhouse.booru.org
0.0.0.0 thepornbin.com
0.0.0.0 theyiffgallery.com
0.0.0.0 toomics.com
0.0.0.0 toomuchgetwrecked.blogspot.com
0.0.0.0 toonily.com
0.0.0.0 tophothere.blogspot.com
0.0.0.0 tour.javhub.com
0.0.0.0 townofsins.com
0.0.0.0 transexualki.ru
0.0.0.0 treenoteca.com
0.0.0.0 u18chan.com
0.0.0.0 ulogin.ru
0.0.0.0 uniondht.org # Uniondht shouldn't be trusted in any shape or form
0.0.0.0 ute.booru.org
0.0.0.0 vdojkah.com
0.0.0.0 verpornocomic.com
0.0.0.0 vi.hentai-img.com
0.0.0.0 vibrolandia.com
0.0.0.0 videomaniaco.com
0.0.0.0 videomonstr.com
0.0.0.0 vidyartplus.booru.org
0.0.0.0 vintagedrawing.com
0.0.0.0 vip-cam.xyz
0.0.0.0 vip-zona.biz
0.0.0.0 vjav.one
0.0.0.0 vk.com
0.0.0.0 vsco.co
0.0.0.0 waifu.booru.org
0.0.0.0 wapbold.escortsporn.com
0.0.0.0 wcili.com
0.0.0.0 wetpussygames.com
0.0.0.0 wetpussyhentai.com
0.0.0.0 wiki.erogames.com
0.0.0.0 worldporncomix.com
0.0.0.0 wowbdsmart.com
0.0.0.0 wowbdsmcomics.com
0.0.0.0 ww1.javbabe.net
0.0.0.0 www.3dxxxcomics.com
0.0.0.0 www.adult-strip-games.com
0.0.0.0 www.adultcomicclub.com
0.0.0.0 www.adultcomicsbook.com
0.0.0.0 www.adultcomicsonly.com
0.0.0.0 www.aiwucm5.cc
0.0.0.0 www.andreauntamed.com
0.0.0.0 www.anime-tube.pw
0.0.0.0 www.assoass.com
0.0.0.0 www.aziani.com
0.0.0.0 www.belrose.eu
0.0.0.0 www.blogr.xxx
0.0.0.0 www.carelessnaked.com
0.0.0.0 www.classicpornscenes.com
0.0.0.0 www.cluset.com
0.0.0.0 www.comicsporn.xxx
0.0.0.0 www.cuntempire.com
0.0.0.0 www.dofantasy.com
0.0.0.0 www.e336.site
0.0.0.0 www.ehentaihip.com
0.0.0.0 www.fairdolls.com
0.0.0.0 www.firstadultgames.com
0.0.0.0 www.free-strip-games.com
0.0.0.0 www.freecomics.xxx
0.0.0.0 www.freegamesexposed.com
0.0.0.0 www.freesexcomics.pro
0.0.0.0 www.furrybeachclub.com
0.0.0.0 www.furryporn.tv
0.0.0.0 www.galacticmonsterquest.com
0.0.0.0 www.gifgoo.com
0.0.0.0 www.girlnude.link
0.0.0.0 www.gold13.top
0.0.0.0 www.greatnass.com
0.0.0.0 www.hentai-gamer.com
0.0.0.0 www.hentai-imperia.org
0.0.0.0 www.hentai.xxx
0.0.0.0 www.hentaidiaries.com
0.0.0.0 www.hentaimovies.me
0.0.0.0 www.hentairing.com
0.0.0.0 www.hentaitorrents.com
0.0.0.0 www.her-calves-muscle-legs.com
0.0.0.0 www.honestpornreviews.com
0.0.0.0 www.hooligapps.com
0.0.0.0 www.horadohomen.com.br
0.0.0.0 www.hornygamer.com
0.0.0.0 www.hotincestart.com
0.0.0.0 www.hotporncomics.com
0.0.0.0 www.hydoll.com
0.0.0.0 www.info-idates.com
0.0.0.0 www.ironchefsworld.com # includes gore
0.0.0.0 www.japanhd.xxx
0.0.0.0 www.javshy.art
0.0.0.0 www.jdavsp.live
0.0.0.0 www.jkforum.net
0.0.0.0 www.johren.net
0.0.0.0 www.jokerlu1.cc
0.0.0.0 www.joylovedolls.com
0.0.0.0 www.jsdolls.com
0.0.0.0 www.justhdporn.com
0.0.0.0 www.kikdolls.com
0.0.0.0 www.ky04.app
0.0.0.0 www.kzmlspq.cn
0.0.0.0 www.lilith-soft.com
0.0.0.0 www.lolicit.org
0.0.0.0 www.lovedollparadise.com
0.0.0.0 www.lovetoys.com.br
0.0.0.0 www.magicmilfcams.com
0.0.0.0 www.maturetube.com
0.0.0.0 www.mdpj.top
0.0.0.0 www.mmofreesex.games
0.0.0.0 www.muscle-girls.net
0.0.0.0 www.musclemistress.com
0.0.0.0 www.myminisexdoll.com
0.0.0.0 www.npns.fr
0.0.0.0 www.nutaku.net
0.0.0.0 www.nutakuaffiliates.com
0.0.0.0 www.ovdoll.com
0.0.0.0 www.paysitesreviews.net
0.0.0.0 www.pg888555.com
0.0.0.0 www.pocketpussy.us
0.0.0.0 www.porncomics.com
0.0.0.0 www.porncomixonline.net
0.0.0.0 www.porndiscounts.com
0.0.0.0 www.pornotorrent.eu
0.0.0.0 www.pov-house.com
0.0.0.0 www.pstargif.com
0.0.0.0 www.pstargif.net
0.0.0.0 www.ptorrents.com
0.0.0.0 www.racyme.com
0.0.0.0 www.redlightcenter.com
0.0.0.0 www.rintor.net
0.0.0.0 www.scateatingfemdom.com
0.0.0.0 www.sexcartoontube.com
0.0.0.0 www.sexdolls.com
0.0.0.0 www.sexdollsoff.com
0.0.0.0 www.sexemulator.com
0.0.0.0 www.sexlikereal.com
0.0.0.0 www.sexsimulator.me
0.0.0.0 www.sextoys.com
0.0.0.0 www.snailsreviews.com
0.0.0.0 www.strip-poker.xxx
0.0.0.0 www.sweetlicious.net
0.0.0.0 www.thecartoonporntube.com
0.0.0.0 www.thevirtualsexreview.com
0.0.0.0 www.tinysexdolls.com
0.0.0.0 www.tktube.com
0.0.0.0 www.toptencams.com
0.0.0.0 www.transhero.com
0.0.0.0 www.truyen-hentai.com
0.0.0.0 www.tumbex.com
0.0.0.0 www.uloversdoll.com
0.0.0.0 www.uplay-istrip.com
0.0.0.0 www.vintage-lingerie.com
0.0.0.0 www.vintagenylons.net
0.0.0.0 www.vintagetwat.com
0.0.0.0 www.vintagia.net
0.0.0.0 www.wnacg.com
0.0.0.0 www.x-zine.de
0.0.0.0 www.xcomics.se
0.0.0.0 www.xxxcomics.me
0.0.0.0 www.xxxcrowlimg.com
0.0.0.0 www.xxxhentai.net
0.0.0.0 www.xxxvintageart.com
0.0.0.0 www.yaoihavenreborn.com
0.0.0.0 www.youngsexdoll.com
0.0.0.0 www.yourdoll.com
0.0.0.0 www2.javdock.com # Yes www2
0.0.0.0 www3.bestjavporn.com
0.0.0.0 www4.javxxx.me
0.0.0.0 x-busty.org
0.0.0.0 x3vid.com
0.0.0.0 xanimu.com
0.0.0.0 xart.letfap.com
0.0.0.0 xcomics.se
0.0.0.0 xhamster.desi # need to block the language too ru.xhamster.desi example
0.0.0.0 xhwide2.com # there are probably more languages for this sites than the ones already in this list
0.0.0.0 xlecx.one
0.0.0.0 xxprime.com
0.0.0.0 xxxgames.games
0.0.0.0 xxxlibz.com
0.0.0.0 xxxparodyhd.net
0.0.0.0 yiffer.xyz
0.0.0.0 zh.hentai-img.com
0.0.0.0 zizki.com

**Comment by DNDEBUG** [comment]
github flagged me so i couldn't do anything but edit it
this list is already outdated, i will update it tomorrow
the new list wont be so organized

**Comment by 1boii** [comment]
Thank you very much for the contribution. Very sorry for the delay.

**Comment by DNDEBUG** [comment]
i hope you keep updating from my list
i got over 1000 sites already
soon to be 2000
